[package]
name = "strata"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { workspace = true }
ash = { workspace = true }
ash-window = { workspace = true }
thiserror = { workspace = true }
